---
- name: Nginx epel-release
  become: true
  ansible.builtin.yum:
    name: epel-release
    state: present

- name: Nginx Install
  become: true
  ansible.builtin.yum:
    name: nginx
    state: present
  notify: Nginx-start

- name: Nginx Configure Template config
  become: true
  ansible.builtin.template:
    src: templates/nginx.conf.j2
    dest: "/etc/nginx/nginx.conf"
    mode: "0777"
  notify: Nginx-reload

- name: LightHouse Mkdir
  become: true
  ansible.builtin.file:
    path: /lighthouse
    state: directory
    mode: "0777"

- name: LightHouse Git pull
  become: true
  ansible.builtin.git:
    repo: "{{ lighthouse_git }}"
    version: master
    dest: "{{ lighthouse_dir }}"

- name: LightHouse Configure Template config
  become: true
  ansible.builtin.template:
    src: templates/lighthouse.conf.j2
    dest: "/etc/nginx/conf.d/default.conf"
    mode: "0777"
  notify: Nginx-reload